### ISSUE TITLE
CoffeeScript + SASS

### ISSUE THREAD

**Issue by ivanthecrazy** [insales/theme_template#1]
Можно ли использовать в темах CoffeeScript и SASS?
У вас же рельсы, я попробовал в редакторе шаблонов (в админке) создать файл custom.js.coffee - таким образом CoffeeScript работает (SPRockets же). Этим можно пользоваться или планируется к выпиливанию?
C SASS такой вариант не прокатывает. Есть ли похожая возможность?

**Comment by kemko** [comment]
Конкретно SASS использовать нельзя, но есть поддержка SCSS. Для этого у файла должно быть расширение .css.scss, а в коде шаблона подключаться должен уже css. Пример SCSS-файла: https://github.com/insales/theme_template/blob/master/test/media/style.css.scss. Подключить его в шаблон можно через конструкцию {{ 'style.css' | asset_url }}.

CoffeeScript поддерживается, выпиливать поддержку в обозримом будущем не планируем, однако использовать его стоит только в случае, если вы пишете шаблон "для себя" или готовы оказывать полную поддержку по шаблону его пользователям. Наша служба техподдержки работает только с JavaScript.

**Comment by ivanthecrazy** [comment]
@kemko Понял, спасибо!
