### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by ururustaru** [insales/theme_template#6]
Добрый день, не могли бы вы поделиться ссылками на более подробное ревью шаблона в readme ?

**Comment by VladimirIvanin** [comment]
Добрый день!
Могу предложить видео где рассказывается про работу с шаблонами:
https://www.youtube.com/watch?v=RUVLRKMdCdo&list=PLKJIxnBHErsDCxrsIlRVYJmKkW0qKB86T

Это поможет вам понять код данного репозитория.
